### ISSUE TITLE
Does it support mms?

### ISSUE THREAD

**Issue by ekstrah** [ibnux/Android-SMS-Gateway#1]
I am not familiar with android app development but wanted to ask whether it supports mms

Best Reagards,

**Comment by ibnux** [comment]
@ekstrah  No, it is not support for MMS
i can add MMS support, but you cannot send FILE from API, because its to big, 
maybe if i use url parameter, and android will download it first, then send it

let me think about it

**Comment by ibnux** [comment]
its hard to support MMS

**Comment by U-siro** [comment]
@ibnux I signed up to your sponsor for this feature!!

**Comment by ibnux** [comment]
Let me see what can i do
