### ISSUE TITLE
invalid ssl certificate

### ISSUE THREAD

**Issue by progressify** [ibnux/Android-SMS-Gateway#12]
on your site: https://sms.ibnux.net/
I receive this error: 

`NET::ERR_CERT_INVALID`

![image](https://user-images.githubusercontent.com/11472632/143595450-08c8dff9-911a-4e31-85c5-30a3718ab2aa.png)

**Comment by ibnux** [comment]
Sorry, forgot to renew SSL, just turnoff cloudflare ssl for all my domain, back to letsencrypt
