### ISSUE TITLE
Local Gateway

### ISSUE THREAD

**Issue by o-data** [ibnux/Android-SMS-Gateway#2]
Question: Can I send SMS through local gateway? From the look of the Readme on https://sms.ibnux.net/ we need to send Post through this URL?

PS: Hi, thank you for making this App.

**Comment by ibnux** [comment]
It's my local gateway
You can use your own gateway, the source for server side included

**Comment by ibnux** [comment]
check backend code for sending push notification

https://github.com/ibnux/Android-SMS-Gateway/tree/master/backend
