### ISSUE TITLE
Received sms has no information on which device and which sim card

### ISSUE THREAD

**Issue by changwuf31** [ibnux/Android-SMS-Gateway#21]
Let's say we have multiple android phones, 
when they receive sms, and send it to the server, how do we know which device has received the sms ?
And if the phone has multiple sim card, which sim slot is the messages received from ?

Best Regards :+1:

**Comment by ibnux** [comment]
I don't know too 😁
I just create apps for my own needs

And its not an issue for me

You can hire me if you need custom apps for your own needs
