### ISSUE TITLE
sms.ibnux.net is down

### ISSUE THREAD

**Issue by freaky666** [ibnux/Android-SMS-Gateway#22]
Seems like sms.ibnux.net is down, still resolves to 103.25.195.242 but is not reachable.

Is Sms.ibnux.net Down?
Checking if sms.ibnux.net is down or it is just you...
It's not just you! sms.ibnux.net is down.

**Comment by ibnux** [comment]
Cloudflare is not connected to my server in Indonesia Jakarta.

Now is connected again

I will create another server using cloudflare workers

![image](https://user-images.githubusercontent.com/811955/177980620-40a62785-0507-4899-89e7-6a07ea0e2984.jpeg)

**Comment by freaky666** [comment]
Indeed, issue has been resolved
