### ISSUE TITLE
Long SMS issue | multiple parts | multiple webhooks

### ISSUE THREAD

**Issue by ramesh-mahesh** [ibnux/Android-SMS-Gateway#27]
How to receive long messages ???

Process: 
when a long sms comes the mobile (3 sms length - 3 parts), it is sending all the three sms's separately  to the web-hook.

Issue: 
when we receive multiple long messages from same sender , I am unable to determine the message part number.

Resolution: 
It would be great if you can send a single web-hook for the entire long message or assign a unique id for each sms send it in the web-hook.

**Comment by ibnux** [comment]
Too many works
And  I don't need it for now

And no github sponsor request it

**Comment by ramesh-mahesh** [comment]
Pleas let me know how to sponsor & how much.

**Comment by hacen-ai** [comment]
Hi @ramesh-mahesh did you find a solution
