### ISSUE TITLE
Backend problems

### ISSUE THREAD

**Issue by tecufanujacu** [ibnux/Android-SMS-Gateway#3]
The backend doesn't seem to work.

$firebasekey shouldn't be called as global in function sendPush?

firebasekey have to be generated in firebase console at this link:
https://console.firebase.google.com/
?

If I correctly understood the steps anyway I have an error with the backend:
{"multicast_id":xxxxxxxxxxxxxxxxxxx,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}

Please could you provide more info about how to use it?

**Comment by ibnux** [comment]
Yes, i forgot about that

i update it
https://github.com/ibnux/Android-SMS-Gateway/commit/2a253e342af58939ddc49dde7a6d82cabe4c7c6d

**Comment by tecufanujacu** [comment]
And what about the error MismatchSenderId? I'm still having it.

**Comment by ibnux** [comment]
You need to create firebase project
And add .json file to android project

And server key in php
Must the same project

From Android studio
Goto Tools -> Firebase 
Connect to firebase
Add Firebase messaging

**Comment by tecufanujacu** [comment]
Oh yes, I only now checked this:
https://github.com/ibnux/Android-SMS-Gateway/blob/master/app/build.gradle

Sorry, I have also opened an issue about not outgoing sms.
