### ISSUE TITLE
sms.ibnux.net is down (no route to host)

### ISSUE THREAD

**Issue by freaky666** [ibnux/Android-SMS-Gateway#30]
Hello it seems like sms.ibnux.net is down, it resolves but no webpage or API access.

Thanks for checking

Is Sms.ibnux.net down?
Checking if sms.ibnux.net is down or it is just you...
It's not just you! [sms.ibnux.net](http://sms.ibnux.net/) is down.

**Comment by ibnux** [comment]
Yes
I think my server crash. And i need to go to datacenter to restart it 😔

**Comment by ibnux** [comment]
You can use my Whatsapp gateway
It's have sms gateway with the same app

https://wa.nux.my.id

**Comment by freaky666** [comment]
Hi, thanks. I did try this but I don't receive a verification code.

Also if you need help with a VM to run this code I can supply this for you.

**Comment by progressify** [comment]
> You can use my Whatsapp gateway It's have sms gateway with the same app
> 
> https://wa.nux.my.id

How it works? Have you also published the code of this gateway?

**Comment by ibnux** [comment]
sorry, i forgot that whatsapp gateway in the same server currently down

sms.ibnux.net is up now, i move to another server, while i am still fixing current server
