### ISSUE TITLE
Can i host this to my own site?

### ISSUE THREAD

**Issue by 0x00chad** [ibnux/Android-SMS-Gateway#5]
i wonder if i can host this to my own site.

**Comment by ibnux** [comment]
@0x00chad yes you can
theres a folder backend 
upload it to your server, edit config same as firebase config
and change application id in android gradle

**Comment by 0x00chad** [comment]
Thank you. ^^ is there a way where you can edit configuration in the android app interface? that you dont need to recompile the application. like theres a textbox in application where you can input your own webserver. thanks for this wonderful app. :)

**Comment by ibnux** [comment]
@0x00chad Android only need to add firebase json configuration and change the aplication_id in gradle.
no need server configuration, because it just listen to push notification send by your server.

server send push notification, android will listen and capture push, then change it to sms

as long the firebase project match, android and backend code will connect

**Comment by 0x00chad** [comment]
can you help me with this i create this php but i want to send this to many number like looping im not good in coding php like it will send to +9234893849,+9349839434 or next line
+9234893849
+9349839445

<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 30px;
  max-width: 50%;
}
</style>
<body>
<div class="container">
<form method="GET">
<br>
<label for="fname">Phone Number</label>
<input cols="50" type="text" name="number"/>
<label for="fname">Message</label>
<input cols="50" type="text" name="message"/> <input type="submit"  name="send" value="Send Message"/><br>
</div>
</form>
</body>
</html>

<?php

//Set to your time zone in phone
date_default_timezone_set('Asia/Taipei');

$time = time();
$deviceID = "f3odmNvIDcs:APA91bGOauhzGqzO0E1LFotOE9_g1q4vDhGlBhDiOYe3ICorN-DCxKJaySsrM_wMFQ4Q6U0WXP-OvkfrbCJSuoZg9OyJizxKwZ1I_usa0e519irJS__8kmxAouPsBQf9pJeilPV7Gkfs";
$secret = "66ba19ca-f99c-46b7-94a8-9afdb297c17d";
//you can hash to md5 to protect your secret, or you just send the secret
$secret = md5($secret.$time);


if(isset($_GET['send']))
{
$number = $_GET['number'];
$message = $_GET['message'];			
echo file_get_contents("https://sms.ibnux.net/?to=".urlencode("$number")."&text=".urlencode("$message")."&secret=$secret&time=$time&deviceID=".urlencode($deviceID));
}
?>

**Comment by 0x00chad** [comment]
here is the link https://pastebin.com/raw/UHDA4iub

**Comment by ibnux** [comment]
this will work

```php
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 30px;
  max-width: 50%;
}
</style>
<body>
<div class="container">
<form method="POST">
<br>
<label for="fname">Phone Number</label>
<input style="width:100%" type="text" name="number" placeholder="number1,number2,number3"/>
<label for="fname">Message</label>
<input cols="50" type="text" name="message"/>
<input type="submit"  name="send" value="Send Message"/><br>
</div>
</form>
<hr>
<pre>
<?php

//Set to your time zone in phone
date_default_timezone_set('Asia/Taipei');

$deviceID = "DEVICE ID";
$secret = "SECRET";
//you can hash to md5 to protect your secret, or you just send the secret

if(isset($_POST['number']) && isset($_POST['message'])){
    $numbers = explode(",",$_POST['number']);
    foreach($numbers as $number){
        echo sendMessage($number, $_POST['message']);
        echo "\n\n";
    }
}

function sendMessage($number, $message){
    global $secret,$deviceID;
    $time = time();
    $secretMd5 = md5($secret.$time);
    return file_get_contents("https://sms.ibnux.net/?to=".urlencode(trim($number))."&text=".urlencode($message)."&secret=$secretMd5&time=$time&deviceID=".urlencode($deviceID));
}
?>

</pre>
</body>
</html>

```

**Comment by 0x00chad** [comment]
Wow thank you very much. your a life saver. :) is there a chance you will add retrieving message from the phone?

**Comment by ibnux** [comment]
I will, if i need to create it, for now I don't need that

Is hard, because to read sms, android apps need to be SMS client, maybe it can if apps read notification.

But is hard to get phone number except don't save the phone number to phonebook, it will show phone number in notification

**Comment by ibnux** [comment]
@0x00chad now the app can read incoming sms and send it to server

**Comment by 0x00chad** [comment]
@ibnux thank you.. is there a way to edit config without compiling the whole apk? like you can edit the config in settings in the app to put your own firebase config..

**Comment by ibnux** [comment]
@0x00chad no it can't
Because it need to change Application ID too
