### ISSUE TITLE
Toggle App status button feature request

### ISSUE THREAD

**Issue by Ajju2211** [ibnux/Android-SMS-Gateway#8]
### Toggle App status button feature request
If their is a button to toggle the app to stop and start.
And if the app is stopped then return status as server down like that.

**Comment by ibnux** [comment]
Better if you toggle from server side or backend

Because you can access backend server from anywhere

**Comment by Ajju2211** [comment]
Actually I need toggle button in the app.
Because the app running all the time and if I want to turn it off then how can I do that.

**Comment by ibnux** [comment]
@Ajju2211 Done
